### ISSUE TITLE
IVLE hosted images in forum posts are not displayed

### ISSUE THREAD

**Issue by xinan** [ymichael/modivle#64]
This is because for images uploaded to IVLE forum, IVLE is only returning the path without hostname, such as 

> /v1/ckeditor/getFile.ashx?id=b89f48d4-9b95-4517-9256-517e710b7ba4&amp;n=Facebook_like_thumb.png

Maybe we can just prepend `ivle.nus.edu.sg` to it if there is no hostname in the url?

**Comment by ymichael** [comment]
Do you mind making a PR? I can't test this because I'm no longer a student :cry:

**Comment by xinan** [comment]
Yeah sure I will try that :smile_cat:
